export const TITLE = {
  APP: 'NutriMate',
  ALL_INFO_BOARD: '전체',
  INFO_BOARD: '정보 공유',
  FOOD_BOARD: '식단',
  SPORT_BOARD: '운동',
  FEED_BOARD: '피드',
  INFO: '자료 공유',
  BOARD_WRITE: '글쓰기',
};

export const PATH_PARAMS = {
  BOARD: 'board',
  ALL: 'all',
  INFO: 'info',
  FOOD: 'food',
  SPORT: 'sport',
  FEED: 'feed',
  WRITE: 'write',
  VIEW: 'view',
  CHALLENGE: 'challenge',
  RECORD: 'record',
  CALENDAR: 'calendar',
  MYINFO: 'mypage',
  BOOKMARK: 'bookmark',
  SETTING: 'setting',
};

//
export const ROUTER_LINKS = {
  BOARD: PATH_PARAMS.BOARD,
  ALL_INFO_BOARD: PATH_PARAMS.INFO + '/' + PATH_PARAMS.ALL,
  FOOD_BOARD: PATH_PARAMS.INFO + '/' + PATH_PARAMS.FOOD,
  SPORT_BOARD: PATH_PARAMS.INFO + '/' + PATH_PARAMS.SPORT,
  FEED_BOARD: PATH_PARAMS.FEED,
  FEED_BOARD_WRITE: PATH_PARAMS.FEED + '/' + PATH_PARAMS.WRITE,
  FEED_BOARD_VIEW: PATH_PARAMS.FEED + '/' + PATH_PARAMS.VIEW,
  INFO: PATH_PARAMS.INFO,
  INFO_BOARD_WRITE: PATH_PARAMS.INFO + '/' + PATH_PARAMS.WRITE,
  INFO_BOARD_VIEW: PATH_PARAMS.INFO + '/' + PATH_PARAMS.VIEW,
  RECORD: PATH_PARAMS.RECORD,
  CALENDAR: PATH_PARAMS.CALENDAR,
  MYINFO: PATH_PARAMS.MYINFO,
  BOOKMARK: PATH_PARAMS.BOOKMARK,
  SETTING: PATH_PARAMS.SETTING,
  CHALLENGE: PATH_PARAMS.BOARD + '/' + PATH_PARAMS.CHALLENGE,
};

export const LINKS = {
  BOARD: '/' + ROUTER_LINKS.BOARD,
  INFO_BOARD: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.INFO,
  ALL_INFO_BOARD: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.ALL_INFO_BOARD,
  FOOD_BOARD: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.FOOD_BOARD,
  SPORT_BOARD: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.SPORT_BOARD,
  FEED_BOARD: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.FEED_BOARD,
  FEEDBOARD_WRITE: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.FEED_BOARD_WRITE,
  FEEDBOARD_VIEW: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.FEED_BOARD_VIEW,
  INFO: '/' + ROUTER_LINKS.INFO,
  INFO_BOARD_WRITE: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.INFO_BOARD_WRITE,
  INFO_BOARD_VIEW: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.INFO_BOARD_VIEW,
  RECORD: '/' + ROUTER_LINKS.RECORD,
  CALENDAR: '/' + ROUTER_LINKS.CALENDAR,
  MYINFO: '/' + ROUTER_LINKS.MYINFO,
  BOOKMARK: '/' + ROUTER_LINKS.BOOKMARK,
  SETTING: '/' + ROUTER_LINKS.SETTING,
  CHALLENGE: '/' + ROUTER_LINKS.CHALLENGE,
};


export const EDITOR_HEIGHT = 500;

export const MENU_LIST = {
  HOME: {
    TITLE: '홈',
    PATH: '/',
  },
  SEARCH: {
    TITLE: '검색',
    PATH: '/',
  },
  RECORD: {
    TITLE: '기록',
    PATH: LINKS.RECORD,
  },
  CALENDAR: {
    TITLE: '캘린더',
    PATH: LINKS.CALENDAR,
  },
  INFOBOARD: {
    TITLE: '공유',
    PATH: LINKS.ALL_INFO_BOARD + '/1',
  },
  FEEDBOARD: {
    TITLE: '피드',
    PATH: LINKS.FEED_BOARD,
  },
  CHALLENGE: {
    TITLE: '챌린지',
    PATH: LINKS.CHALLENGE,
  },
  MYINFO: {
    TITLE: '프로필',
    PATH: LINKS.MYINFO,
  },
  BOOKMARK: {
    TITLE: '북마크',
    PATH: LINKS.BOOKMARK,
  },
  SETTING: {
    TITLE: '설정',
    PATH: LINKS.SETTING,
  },
};

