export const TITLE = {
  APP: 'NutriMate',
  ALL_INFO_BOARD: '전체',
  INFO_BOARD: '정보 공유',
  FOOD_BOARD: '식단',
  SPORT_BOARD: '운동',
  FEED_BOARD: '피드',
  INFO: '자료 공유',
  BOARD_WRITE: '글쓰기',
};

export const PATH_PARAMS = {
  BOARD: 'board',
  ALL: 'all',
  INFO: 'info',
  FOOD: 'food',
  SPORT: 'sport',
  FEED: 'feed',
  WRITE: 'write',
  VIEW: 'view',
};

//
export const ROUTER_LINKS = {
  BOARD: PATH_PARAMS.BOARD,
  ALL_INFO_BOARD: PATH_PARAMS.INFO + '/' + PATH_PARAMS.ALL,
  FOOD_BOARD: PATH_PARAMS.INFO + '/' + PATH_PARAMS.FOOD,
  SPORT_BOARD: PATH_PARAMS.INFO + '/' + PATH_PARAMS.SPORT,
  FEED_BOARD: PATH_PARAMS.FEED,
  INFO: PATH_PARAMS.INFO,
  INFO_BOARD_WRITE: PATH_PARAMS.INFO + '/' + PATH_PARAMS.WRITE,
  INFO_BOARD_VIEW: PATH_PARAMS.INFO + '/' + PATH_PARAMS.VIEW,
};

export const LINKS = {
  BOARD: '/' + ROUTER_LINKS.BOARD,
  INFO_BOARD: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.INFO,
  ALL_INFO_BOARD: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.ALL_INFO_BOARD,
  FOOD_BOARD: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.FOOD_BOARD,
  SPORT_BOARD: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.SPORT_BOARD,
  FEED_BOARD: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.FEED_BOARD,
  INFO: '/' + ROUTER_LINKS.INFO,
  INFO_BOARD_WRITE: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.INFO_BOARD_WRITE,
  INFO_BOARD_VIEW: '/' + ROUTER_LINKS.BOARD + '/' + ROUTER_LINKS.INFO_BOARD_VIEW,
};


export const EDITOR_HEIGHT = 500;



